import type { Metadata } from "next";
import "./globals.css";

import { Kiwi_Maru } from '@next/font/google';

const kiwiMaru = Kiwi_Maru({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Rifa Casa Nova",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kiwiMaru.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
